<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Programmatically_get_differences</RootNamespace>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="Syncfusion.EJ2.AspNet.Core" Version="*" />
  </ItemGroup>
</Project>
